### ISSUE TITLE
High CPU usage when idle caused by AnimatedProgressBar

### ISSUE THREAD

**Issue by pocmo** [mozilla-tw/FirefoxLite#2454]
See this issue:
https://github.com/mozilla-mobile/android-components/issues/622

I noticed that Rocket is affected too. Rocket does not use the `ui-progress` component yet. So a fix would need to be applied to the Rocket repository manually.

On my Nexus 9 Rocket is using about 10% - 20% of CPU while idling just because of AnimatedProgressBar.

**Comment by pocmo** [comment]
FYI: We released a patch that fixes this in 0.19.1 of the components. Maybe it would be an option for you to replace AnimatedProgressBar with `ui-progress`.

**Comment by chianger** [comment]
battery consumption issue: S1.

**Comment by chianger** [comment]
action item: investigate whether take the fix from android component.

**Comment by cnevinc** [comment]
After some testing, I didn't find the problem at our code base. Could it be the implementation of the reference browser is different with Lite?
Below is the CPU trace after loading Bukalapak and wait for some time.
The peak after the first load is caused by the banner switching in the website.
onAnimationUpdate only happens at the beginning.
![image](https://user-images.githubusercontent.com/1287363/50370929-2b18a680-05eb-11e9-9178-9fb7c315ea4d.png)

And this is the loading of wikipeida
Call Chart:
![image](https://user-images.githubusercontent.com/1287363/50371542-d3346c80-05f7-11e9-9e84-af677a4889bd.png)
 
Flame Chart:
![image](https://user-images.githubusercontent.com/1287363/50371588-acc30100-05f8-11e9-8272-486de80c6d0d.png)

**Comment by cnevinc** [comment]
Another testing on API 24 emulator
After loading wikipedia.com, I didn't see any CPU usage

![image](https://user-images.githubusercontent.com/1287363/50372386-a9377600-0608-11e9-9a7e-54e59d621eea.png)

**Comment by cnevinc** [comment]
Turns out there's an infinite loop (here)[https://github.com/mozilla-tw/Rocket/blob/d28a15cf244e87a039377c98e8da65f73691d609/app/src/main/java/org/mozilla/focus/widget/ShiftDrawable.java#L41
]
If we set `mAnimator.setRepeatCount(ValueAnimator.INFINITE);` then `onAnimationUpdate` will always be called.  

The PR here works when the web page load completed. But will kick off the loop again once the user move the app to the background.

I've tried `clearAnimation` on AnimatedProgressBar but it didn't help. I'm don't know what's the best timing to make ShiftDrawable's visiblity to false. (it'll change to true by unknow source)

Worst case is to comment out the infinite repeat unless I found a better solution.

**Comment by Daisy-pliu** [comment]
Verify : ✅
Test and compare on CPU usage on profiler via Android Studio 
Test step: 
1. install [Bitrise#9085](https://app.bitrise.io/build/c9461e30b7bc58dc) (build with fix) and track profiler on Android Studio
2. install [Bitrise#9076](https://app.bitrise.io/build/09a18a680a6d155e) (build without fix)and track profiler
3. Compare CPU usage by searching onAnimationUpdate

**Comment by Daisy-pliu** [comment]
Verify: ✅
Test step: 
1. set up profiler on Android Studio(refer [CPU performance](https://developer.android.com/studio/profile/android-profiler))
2. record 40 sec after click WIKIpage
3. compare the CPU usage for "onAniamtionUpdate()"in this build with previous build

Test Result:
Before:
<img width="1150" alt="screen shot 2019-02-25 at 5 21 02 pm" src="https://user-images.githubusercontent.com/44990878/53327719-54bfb800-3923-11e9-9b2b-6c6275b4d950.png">
After:
<img width="1160" alt="screen shot 2019-02-25 at 5 22 57 pm" src="https://user-images.githubusercontent.com/44990878/53327722-56897b80-3923-11e9-85fe-96966abe4663.png">
