### ISSUE TITLE
Incorrect link of Get Community Support

### ISSUE THREAD

**Issue by Daisy-pliu** [mozilla-tw/FirefoxLite#3004]
**Describe the bug**
After clicking [Ask a Question] button, user should see product is [Firefox] in the page

**Steps To Reproduce**
1. Launch app 
2. Click [Settings]
3. Click [About]
4. Click [Support]
5. Click [Back to: Firefox Lite]
6. Click [Get community Support]
7. Click [GET HELP]

**Expected behavior**
Default selected product is [Firefox Lite]

**Actual behavior**
Default selected product is [Firefox for Android]

**Screenshots/videos**
https://drive.google.com/open?id=1NUzqFTw_HuMJ6DcJCHyepJOW3PDAGPfe

**Device info (please complete the following information):**
 - Device: Samsung galaxy S7 edge
 - OS: Android 7.0
 - Webview: 70.3538.110
 - Version: 1.0.4(8798)

**Refer on Slack**
https://mozilla.slack.com/archives/C6NHAKGQ3/p1545029696072000

**Comment by SeburoSUMO** [comment]
Hi @Daisy-pliu 

That looks spot on.  

I see the same behaviour in Firefox Lite 1.0.4(8824).nightly, WebView version 71.0.3578.98 on Android 8.0.0.

I believe that this is possibly a very good reason why we are seeing very few support requests for this product in SUMO.

I think that this issue is being driven by the user agent.  If the Fx Lite UA is changed, we will need to configure Kitsune (the SUMO platform) to pick this up.

**Comment by chianger** [comment]
forked on bugzilla to call out to SUMO team https://bugzilla.mozilla.org/show_bug.cgi?id=1515569

**Comment by chianger** [comment]
flow improvement.

**Comment by pmac** [comment]
Hi. SUMO engineer here. Looking at this line in the code it looks like the target of the [support] link in question here is for the mobile "rocket-help" topic:

https://github.com/mozilla-tw/Rocket/blob/38b60e2f171004300fa13856907d4b5636475a2c/app/src/main/java/org/mozilla/focus/utils/SupportUtils.java#L221

In SUMO this is currently a redirect to https://support.mozilla.org/products/firefox-lite/get-started. I think the issue then is that we'd like the "get community support" button on [this page](https://support.mozilla.org/products/firefox-lite) to link directly to the Firefox Lite product instead of generic support. Sound right?

**Comment by jpetto** [comment]
We have a potential fix up on the dev site:

https://dev.sumo.moz.works/questions/new

I do not have an Android device to test with - can someone hit the above URL using Firefox Lite and see which product is selected?

(I did manually edit my user string to Rocket nightly (see below) and did get Firefox Lite selected.)

`Mozilla/5.0 (Linux; Android 8.0.0; moto e5 Build/OPP27.91-176; rv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Rocket/1.0.9(9399).nightly Chrome/71.0.3578.99 Mobile Safari/537.36`

**Comment by mTwTm** [comment]
I think lite and lite nightly both direct to lite if I understood this page correctly. (I clicked new issue and it directs me to an url that contains firefox-lite.)

**Comment by mTwTm** [comment]
BTW lite (release) 's UA is `Mozilla/5.0 (Linux; Android 9; Nokia 5.1 Plus Build/PPR1.180610.011; rv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Rocket/1.0.8(9248) Chrome/71.0.3578.99 Mobile Safari/537.36`

**Comment by jpetto** [comment]
> I think lite and lite nightly both direct to lite if I understood this page correctly. (I clicked new issue and it directs me to an url that contains firefox-lite.)

Is this the expected/correct behavior? (I believe it is, but please tell me if I'm wrong.)

**Comment by jpetto** [comment]
@mTwTm Do you know if the UA string will continue to include `Rocket` going forward? Or will `Rocket` be changed to `Lite` at some point?

**Comment by mTwTm** [comment]
> Is this the expected/correct behavior? (I believe it is, but please tell me if I'm wrong.)
Nightly is currently more of a non-public distribution so I will say yes.
> Do you know if the UA string will continue to include Rocket going forward? Or will Rocket be changed to Lite at some point?
No the change is intentionally not planned during the re-brand and I believe it's not going to change as well in forseeable future.

**Comment by chianger** [comment]
Resolved FIXED
