### ISSUE TITLE
Create private browsing app shortcut - HomeScreen

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3184]
// based on Focus UR

**User story**
As a user, I would like to access Private Browsing as quick and convenient as possible through a simple tap

**Acceptance Criteria (how do I know when I’m done?)** 
1.
2.
3.

**Additional context**

**Comment by TLHuang** [comment]
The assets are ready, please download here [ic_pb_launcher.zip](https://github.com/mozilla-tw/FirefoxLite/files/3155421/ic_pb_launcher.zip)

**Comment by Jacklin-ux** [comment]
UX spec:https://drive.google.com/file/d/13uV9WkfBCq1Djb1Us250HAk-SHbji6qH/view?usp=sharing

**Comment by TLHuang** [comment]
Visual spec: https://zpl.io/29wXqvd

**Comment by chianger** [comment]
MVP Scope: suggest to make user adding Private browsing to homescreen

**Comment by Daisy-pliu** [comment]
private browsing shortcut to home screen test case is ready [TC0231 -TC0233](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B336)

**Comment by chianger** [comment]
telemetry-wanted to know the count of user triggering private browsing with the shortcut.

**Comment by chianger** [comment]
Apart from above comment, two more pieces might be worth adding: 
2. UI telemetry of the prompt dialog
3. UI telemetry of Setting > add private mode shortcut to home screen

**Comment by elin-moco** [comment]
@pharspher @chianger 
As per discussed with Lany, 
the telemetry definition below:

1. App is launched from Private Shortcut
 - method=launch, object=app, value=private_mode, extra={from: launcher|external_app, type=text_selection|web_search)
2. Show private shortcut prompt
 - method=show, object=private_shortcut, extra={mode=private_mode}
3. Click private shortcut prompt
 - method=click, object=private_shortcut, value=dismiss|positive|negative, extra={mode=private_mode}
4. Users clicked on a Setting
 -  method=click, object=settings, value=pref_private_shortcut
5. Exit private mode
 - method=click, object=private_mode, value=exit, extra={from=system_back, mode=private_mode}
6. Private shortcut created
 - method=pin_shortcut, object=private_shortcut, extra={mode=private_mode}

**Comment by elin-moco** [comment]
As per discussion with Roger, added 7. kill app

**Comment by chianger** [comment]
data review request to @cnevinc :

    What questions will you answer with this data?
    We want to know how user interacts with the "private browsing" (a.k.a content portal) function, and the shortcut on homescreen to enter private browsing. Checking the UI interactions only.

    Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements?
    We need more information from the user so we can enhance the user experience  and also further make plan for new features

    What alternative methods did you consider to answer these questions? Why were they not sufficient?
    We don't have any other than user survey, but that is not enough to get granular detailed data.

    Can current instrumentation answer these questions?
    No.

    List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories on the Mozilla wiki.
    Category 2 “Interaction data”

    How long will this data be collected? Choose one of the following:
    We want to collect this data for 6 months initially and then decide if we want this data to be collected going forward.

    What populations will you measure?
    Users in targets markets where Lite ships to.

    If this data collection is default on, what is the opt-out mechanism for users?
    The user can disable "Send usage data" in settings to opt-out.

    Please provide a general description of how you will analyze this data.
    We'll use Firebase, Amplitude and STMO. Comparing conversion rate, retention rate and the usage over time.

    Where do you intend to share the results of your analysis?
    N/A. Data is for internal feature planning evaluation only

**Comment by cnevinc** [comment]
> data review request to @cnevinc :

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way? 
yes.

2) Is there a control mechanism that allows the user to turn the data collection on and off?
yes (Send Usage Data)

3) If the request is for permanent data collection, is there someone who will monitor the data over time?
@joechengla and @elin-moco 

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?
2

5) Is the data collection request for default-on or default-off?
default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
no

7) Is the data collection covered by the existing Firefox privacy notice? **If unsure: escalate to legal if:**
yes

8) Does there need to be a check-in in the future to determine whether to renew the data? (Yes/No) (If yes, set a todo reminder or file a bug if appropriate)**
no

9) Does the data collection use a third-party collection tool? **If yes, escalate to legal.**
Amplitude and Firebase. But they are covered in the privacy notice.

**Comment by Daisy-pliu** [comment]
verify: ✅
Test device: samsung 8.0
test case: TC0231~TC0233

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version: 1.7.0 (12606)nightly
Test device: samsung 8.0
test case: TC0231~TC0233

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version: 1.7.0 (12623)RC
Test device: samsung 8.0
test case: TC0231~TC0233
