### ISSUE TITLE
Use Firebase as switch to pref on/off life feed for users

### ISSUE THREAD

**Issue by chianger** [mozilla-tw/FirefoxLite#3289]
**User story**
As life feed service provider, I would like to be able to use Firebase as kill switch to pref on/off life feed

**Acceptance Criteria (how do I know when I’m done?)** 
1. Separate RemoteConfig from "Send Usage Data" and make remote config "Always On"
2. Firebase remote config and attribute in place for toggling on/off life feed
3. Users fall into the 'off' group shall not see life feed
3. This should work for both e-commerce and News.

**Comment by chianger** [comment]
i believe this was closed accidentally.

**Comment by cnevinc** [comment]
We previously had a discussion. If we want to use Firebase RemoteConfig to enable News features, if the user disables "Send Usage Data" he won't be able to see the news. This will confuse the user unless we separate  RemoteConfig from "Send Usage Data" and make remote config "Always On"

Anyway, I'll update the description to make it more clear.

**Comment by Daisy-pliu** [comment]
News portal remote config test case
SC1 Able to turn switch off:
1. Given Firebase parameter [portal_news] switch is [on]
2. Set [portal_news] to [off] in remote config panel

**Comment by Daisy-pliu** [comment]
News portal remote config test case.

**SC1 Upgrade from 1.3.1 to latest & set news portal ON**
1. Given Firebase parameter [portal_news] switch is [off]
2. Install version 1.3.1 
3. Set [portal_news] to [on] in remote config panel 
4. Upgrade app
5. see [news on boarding page]
6. skip news onboarding page
7. Swipe up to see [news portal]
8. Tap [menu]->[setting] to see [news source]
9.  Tap [about] to see [learn more about life feed]
10. Set [portal_news] to [off] in remote config panel 
11. Relaunch app 
12. back to home page to check [no news portal]
13. Tap [menu]->[setting] to check no [news source]
14. Tap [about] to check no [learn more about life feed]



**SC2 Upgrade from 1.3.1 to latest & set news portal OFF**
1. Given Firebase parameter [portal_news] switch is [on]
2.  Install 1.3.1
3. Set [portal_news] to [off] in remote config panel 
4.  Upgrade app
5. Check no onboarding page
6. Swipe up to check [no news portal]
7. Tap [menu]->[setting] to see [ no news source]
8. Tap [about] to see [no learn more about life feed]
9.  Set [portal_news] to [on] in remote config panel 
10. Relaunch app 
11. back to home page and swipe up to see [news portal]
12. Tap [menu]->[setting] to check [news source]
13. Tap [about] to check [learn more about life feed]




**SC3 Upgrade from 1.2.0 to latest & set news portal ON**
1. Given Firebase parameter [portal_news] switch is [off]
2. Install 1.2.0
3. Set [portal_news] to [on] in remote config panel 
4. Upgrade app
5. Should not see [news on boarding page]
6. Swipe up to see [news portal]
7. Tap [menu]->[setting] to see [news source]
8. Tap [about] to see [learn more about life feed]
9.  Set [portal_news] to [off] in remote config panel 
10. Relaunch app 
11. back to home page to check [no news portal]
12. Tap [menu]->[setting] to check [no news source]
13. Tap [about] to check [no learn more about life feed]


**SC4 Upgrade from 1.2.0 to latest & set news portal ON**
1. Given Firebase parameter [portal_news] switch is [off]
2. Install 1.2.0
3. Set [portal_news] to [on] in remote config panel 
4. Upgrade app
5. Should not see [news on boarding page]
6. Swipe up to see [news portal]
7. Tap [menu]->[setting] to see [news source]
8. Tap [about] to see [learn more about life feed]
9.  Set [portal_news] to [off] in remote config panel 
10. Relaunch app 
11. back to home page to check [no news portal]
12. Tap [menu]->[setting] to check [no news source]
13. Tap [about] to check [no learn more about life feed]

**Comment by Daisy-pliu** [comment]
**verify:** ✅
**Test version:** 1.2.1(110373).nightly
**test step**
1. set "enable_life_feed= true " when "country=india"
2. launch app on phone with India SIM to see "news portal onboarding"
3. swipe up to see [news]
4. go to [settings] to see [news source] 
5. go to [about] to see [learn more about life feed]
6. set "enable_life_feed= false " when "country=india"
7. clear app data in system
8. launch app
9. there is [no news onboarding]
9. user should [not see swipe up arrow]
10. go to [settings] user [not  see news source] 
11. go to [about] user not see [learn more about life feed]?  @Jacklin-ux

**Comment by Daisy-pliu** [comment]
per discussion with @Jacklin-ux , as the redirected page mentioned news portal only applies on India, we decide to keep it.

**Comment by Daisy-pliu** [comment]
verify: ✅
Test version :1.3.0 (11070)
Test device :Samsung 8.0
Test pre-condiction: mobile with India SIM 

**SC1 Upgrade from 1.1.3 to latest & set news portal ON**
1. Given Firebase parameter [portal_news] switch is [off]
2. Install version 1.3.1 
3. Set [portal_news] to [true] in remote config panel 
4. Upgrade app
5. see [news on boarding page] 
6. skip news onboarding page
7. Swipe up to see [news portal]
8. Tap [menu]->[setting] to see [news source]
9.  Tap [about] to see [learn more about life feed]
10. Set [portal_news] to [false] in remote config panel 
11. wait 1 hour and then Relaunch app 
12. back to home page to check [no news portal]
13. Tap [menu]->[setting] to check no [news source]
14. Tap [about] to check no [learn more about life feed]

Note: 
Step 5 it will not show [news on boarding page] due to the remote config delay 


**SC2 Upgrade from 1.1.3 to latest & set news portal OFF**
1. Given Firebase parameter [portal_news] switch is [on]
2.  Install 1.3.1
3. Set [portal_news] to [off] in remote config panel 
4.  Upgrade app
5. Check no onboarding page
6. Swipe up to check [no news portal]
7. Tap [menu]->[setting] to see [ no news source]
8. Tap [about] to see [no learn more about life feed]
9.  Set [portal_news] to [on] in remote config panel 
10. wait 1 hour and then Relaunch app 
11. back to home page and swipe up to see [news portal]
12. Tap [menu]->[setting] to check [news source]
13. Tap [about] to check [learn more about life feed]


**SC3 Upgrade from 1.2.1 to latest & set news portal ON**
1. Given Firebase parameter [portal_news] switch is [off]
2. Install 1.2.1
3. Set [portal_news] to [on] in remote config panel 
4. Upgrade app
5. Should not see [news on boarding page]
6. Swipe up to see [news portal]
7. Tap [menu]->[setting] to see [news source]
8. Tap [about] to see [learn more about life feed]
9.  Set [portal_news] to [off] in remote config panel 
10. wait 1 hour and then Relaunch app 
11. back to home page to check [no news portal]
12. Tap [menu]->[setting] to check [no news source]
13. Tap [about] to check [no learn more about life feed]


**SC4 Upgrade from 1.2.1 to latest & set news portal OFF**
1. Given Firebase parameter [portal_news] switch is [on]
2. Install 1.2.1
3. Set [portal_news] to [off] in remote config panel 
4. Upgrade app
5. Should  see [no news onboarding page]
6. Swipe up to see [no news portal]
7. Tap [menu]->[setting] to see [news source]
8. Tap [about] to see [learn more about life feed]
9.  Set [portal_news] to [on] in remote config panel 
10. wait 1 hour and then Relaunch app 
11. back to home page to check [news portal]
12. Tap [menu]->[setting] to check [news source]
13. Tap [about] to check [learn more about life feed]
