### ISSUE TITLE
Improve conversion from FxLite Home to Life Feed 

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#3402]

**Comment by chianger** [comment]
status: running survey to dig out some insight.

**Comment by chianger** [comment]
If we do such enhancement, should also consider reducing current onboarding slide of life feed.

**Comment by Jacklin-ux** [comment]
UX spec: https://drive.google.com/file/d/1YzqN0e-R7b7pcFUrYE_g_uIpRpGVNzd5/view?usp=sharing

**Comment by TLHuang** [comment]
Visual spec and asset are updated, link here https://zpl.io/2GGWMMr
Let me know if any questions!

**Comment by Daisy-pliu** [comment]
Refactor test case on India life feed on boarding [TC0213](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B313), indo life feed onboarding [TC0219, TC0219-2](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B328)

**Comment by Daisy-pliu** [comment]
verify: ❓
This works on indo and india user that they can see [contextual on boarding] without [color yourlife].
However the rest countries user can not see [color your life] anymore.
TC0213: ✅
TC0219: ✅
TC0001 ❌
Test step:
1. vpn in Australia
2. fresh install latest nightly 11964

Test result
can not see [color your life]
@Jacklin-ux  not sure it is acceptable from UX perspective ?

**Comment by Jacklin-ux** [comment]
If don't have Life feed contextual onboarding, I expect to see Color your life onboarding. But for now, it's fine and not a blocker.

**Comment by Daisy-pliu** [comment]
We have not make release build so even it is not blocker we still have time fix it. I will set it verify fail.

**Comment by benjamin-cheng** [comment]
I was confused that due to some reason (What I think was it's not so important so also de-feature in this issue XD), the "Color your life" onboarding is removed from both india and Indonesia user, why is it necessary to keep the onboarding screen to the other users? @Jacklin-ux If "Color your life" onboarding is must-have feature, should we add it back to the India and Indonesia user as well? (of course NOT show the both onborading at the same time)

On the other hand, from the implementation perspective, since the remote config is sync from the internet so it might be delayed or encounter any network issues, we cannot guarantee to show only the life feed onboarding for those users with content portal enable if we also have to keep the "Color your life" onboarding for the other users without content portal feature.

If we need keep the "Color your life" onboarding, the best we can do is:

* If content portal is enable and the remote config is retrieved right before we need to decide which onboarding to show...
Fresh install => Life feed onboarding => next app launch => No other onboarding is shown

* If content portal is enable however the config is NOT retrieved before we need to decide which onboarding to show...
Fresh install => Color your life onborading => next app launch => Life feed onboarding 

* If content portal is NOT enable...
Fresh install => Color your life onborading => next app launch => No other onboarding is shown


For simplicity, we suggest to either remove or keep "Color your life" onboarding globally.

**Comment by Jacklin-ux** [comment]
Ok, thank you for the feedback. I can agree with removing color your life for all countries, and I will think about how to redesign this in the near future.

**Comment by Daisy-pliu** [comment]
**Verify:** ✅
This works on indo and india user that they can see [contextual on boarding] without [color yourlife].
However the rest countries user wont see [color your life] anymore.
TC0213: ✅
TC0219: ✅
**Version**
11964 nightly

**Comment by Daisy-pliu** [comment]
**Verify:** ✅
**Test case:**
TC0213: ✅
TC0219: ✅
**Version**
1.6.0 (12105)
