### ISSUE TITLE
[Travel] The font weights in Google search results and smart travel search results are not consistent

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-tw/FirefoxLite#4426]
**Describe the bug**
The font weights of matched text are not consistent. 
1. Matched text in google search results is bolder.
2. Matched Chinese text isn't bold.

**Comment by tinahsieh** [comment]
Can we get the refined UIs for our visual designer, @FinnickC, to review?

**Comment by benjamin-cheng** [comment]
Since the highlight effect is not so obvious on Chinese keyword, confirmed with @tinahsieh it would need to apply the `BOLD` typeface like exactly what we did for shopping search keyword highlight. @hartsu Could you please help to work on the refinement and please provide the both English and Chinese keyword highlight screenshot after you've finished the change. Thank you!

**Comment by hartsu** [comment]
Please refer to the following English and Chinese keyword highlight screenshots.
![Screenshot_1576052306](https://user-images.githubusercontent.com/1251503/70605439-75989600-1c35-11ea-9943-306d44185683.png)
![Screenshot_1576052333](https://user-images.githubusercontent.com/1251503/70605440-76312c80-1c35-11ea-8d40-c9b5388ab283.png)

**Comment by FinnickC** [comment]
ok!!looks good to me.

**Comment by benjamin-cheng** [comment]
@FinnickC 👍
