### ISSUE TITLE
each time I open this browser, it does automatically open TOKOPEDIA apps

### ISSUE THREAD

**Issue by joechengla** [mozilla-tw/FirefoxLite#4500]
https://play.google.com/apps/publish?account=7083182635971239206#ReviewDetailsPlace:p=org.mozilla.rocket&reviewid=gp:AOqpTOHUqDvpP8cwiQbtIYSpavF5DarSTPEi5Tpz35eQ9thlbNrU3XIQY95fUXwMrBi5t_k9IepbWume-Q1t1iI

**Comment by Conjuror** [comment]
**STR**
_Prerequisite_
1. TOKOPEDIA is installed in app

_STR_
1. Launch Firefox Lite
2. Tap on [TOKOPEDIA] in top sites (switch to Indonesia to show TOKOPEDIA in top sites)
3. Kill Firefox Lite from Recent App
4. Launch Firefox Lite

_Expected Result_
4. Launch Firefox Lite and stay in App entry page

_Actual Result_
4. TOKOPEDIA is started after a while

**Environment**
_Set 1_
Android 5.1
2.0.5 (17500)

_Set 2_
Android 8
2.0.4 (17564)

**Comment by chianger** [comment]
action: need UX to define behavior

**Comment by chianger** [comment]
The expected behavior is clear that we don't want APP to bring up immediately. 
But not clear what else side effects comes from that behavior change. It requires discussion with devs.

**Comment by shsu571** [comment]
engineer suggestion: use prompt to ask user

**Comment by tinahsieh** [comment]
After confirmed with @Conjuror and @benjamin-cheng, I realized that we should separate this issue into two : bug and new feature (showing a prompt/ snack bar).
1. **Bug**: Firefox Lite should not preload links, which open apps, in background.
2. **New feature**: Firefox Lite should show a prompt/ snack bar when it's going to open an app instead of a website, so that users will know that they're leaving Firefox Lite.

I'll open an issue for the new feature.

**Comment by shsu571** [comment]
3/2 Discussion
will need to study : when users get back and see the preload blank page
Options:
1. Kill tab
2.Open App 
3.white page

**Comment by Conjuror** [comment]
18876. Verified.
