### ISSUE TITLE
Data Review Request - MSRP Data Review

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4589]
MSRP (by Mark Liang)
1. What questions will you answer with this data?
We want to know how user interacts with our new reward feature including completing the challenges and redeeming the rewards.

2. Why does Mozilla need to answer these questions? Are there benefits for users? Do we need this information to address product or business requirements? Some example responses:
We need to determine whether a reward feature has an effect on user’s behaviors on our platform, and get more information for advancing our business objectives such as generating/optimizing revenue from content and services.

3. What alternative methods did you consider to answer these questions? Why were they not sufficient?
We don't have any other than user survey, but that is not enough to get granular detailed data.

4. Can current instrumentation answer these questions?
No

5. List all proposed measurements and indicate the category of data collection for each measurement, using the Firefox data collection categories found on the Mozilla wiki.
All the 11 pings here for review (listed below) are Category 2 “Interaction data”.

6. How long will this data be collected? Choose one of the following:
This is scoped to a time-limited experiment/project until date 12-31-2019.

7. What populations will you measure?
The measurement for this feature is exclusively for our Indonesian users.

8. If this data collection is default on, what is the opt-out mechanism for users?
Users can disable "Send usage data" in settings to opt-out.

9. Please provide a general description of how you will analyze this data.
We'll use Firebase, Amplitude and backend database. Comparing conversion rate, retention rate ,the completion rate and user flow finished rate over time.

10. Where do you intend to share the results of your analysis?
Not for sharing. The data is for internal feature planning evaluation only.

11. Is there a third-party tool (i.e. not Telemetry) that you are proposing to use for this data collection?
Firebase.

**Comment by youwenliang** [comment]
group | No | Dat Cat. | detail
-- | -- | -- | --
MSRP | M01 | Cat 2: “Interaction data” | \|Click Challenge Page Join\|action\|click\|challenge_page\|"join"\|""
MSRP | M02 | Cat 2: “Interaction data” | \|Show Task Contextual Hint\|action\|show\|contextual_hint\|"task"\|""
MSRP | M03 | Cat 2: “Interaction data” | \|End Task\|action\|end\|task\|""\|"task=[0-9]+,finished=false\|true,"
MSRP | M04 | Cat 2: “Interaction data” | \|Show Challenge Complete Message\|action\|show\|message\|"challenge_complete"\|""
MSRP | M05 | Cat 2: “Interaction data” | \|Click Challenge Complete Message\|action\|click\|message\|"challenge_complete"\|"action=dismiss\|later\|login\|close,"
MSRP | M06 | Cat 2: “Interaction data” | \|Account Sign In\|action\|sign_in\|account\|""\|""
MSRP | M07 | Cat 2: “Interaction data” | \|Show Redeem Page\|action\|show\|redeem_page\|""\|""
MSRP | M08 | Cat 2: “Interaction data” | \|Copy Code on Redeem Page\|action\|copy\|redeem_page\|"code"\|""
MSRP | M09 | Cat 2: “Interaction data” | \|Click Redeem on Redeem Page\|action\|click\|redeem_page\|"use"\|""
MSRP | M10 | Cat 2: “Interaction data” | \|Click Reward Profile\|action\|click\|profile\|"reward"\|""
MSRP | M11 | Cat 2: “Interaction data” | \|Click Item Content Home\|action\|click\|content_home\|"item"\|"category=mission\|gift,item_name=item name,"
MSRP | M12 | Cat 2: “Interaction data” | \|Click Chellenge Page Login\|action\|click\|challenge_page\|"login"\|""

**Comment by cnevinc** [comment]
To be more specific, the user will send out the data to our backend when they join the mission and do daily check-in. If the user quit the mission, it will depend on "Send usage data" to determine if we still send out the event to our Telemetry server or not. R+

1) Is there or will there be **documentation** that describes the schema for the ultimate data set in a public, complete, and accurate way?  
yes

2) Is there a control mechanism that allows the user to turn the data collection on and off? 
yes. There's a "Send usage data " option in the settings page.

3) If the request is for permanent data collection, is there someone who will monitor the data over time?
@joechengla @elin-moco @lanyliu 

4) Using the **[category system of data types](https://wiki.mozilla.org/Firefox/Data_Collection)** on the Mozilla wiki, what collection type of data do the requested measurements fall under?
Category 2

5) Is the data collection request for default-on or default-off?
default on

6) Does the instrumentation include the addition of **any *new* identifiers** (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?
no

7) Is the data collection covered by the existing Firefox privacy notice? 
yes

8) Does there need to be a check-in in the future to determine whether to renew the data? 
Yes. https://github.com/mozilla-tw/FirefoxLite/issues/4588

9) Does the data collection use a third-party collection tool? 
Yes(Firebase). But this is covered in the Privacy Notice
