### ISSUE TITLE
Adjust the contrast of the gray buttons in News

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4654]
The gray button in the "No, thanks" button in Recommended News onboarding is not visible enough. And the gray buttons in the preferred languages are also not visible enough.

Need VD to update the spec to change the colors.
![image](https://user-images.githubusercontent.com/8919308/72589547-8a540200-3936-11ea-8d5c-b9a5e9d59b0e.png)

![image](https://user-images.githubusercontent.com/8919308/72589535-83c58a80-3936-11ea-89b0-73bd41eba932.png)

**Comment by TLHuang** [comment]
Visual spec https://app.zeplin.io/project/5d3e6ee752e9500d60e1f07e/dashboard?tag=4654
Let me know if any questions.

**Comment by TLHuang** [comment]
Just notice that based on the visual spec, the style of "NO, THANKS" button should use border instead of drop shadow. @benjamin-cheng are we able to fix this?
![Screenshot_2020-01-20-16-13-14-694_org mozilla rocket beta](https://user-images.githubusercontent.com/4092794/72710047-2c772280-3ba1-11ea-9860-7888948be9a8.jpg)

**Comment by benjamin-cheng** [comment]
@TLHuang could you help to verify it again with latest nightly build? Thank you!

![device-2020-01-22-103252](https://user-images.githubusercontent.com/7045016/72860744-bd194400-3d02-11ea-8237-eebc5b697967.png)

**Comment by youwenliang** [comment]
@benjamin-cheng Looks good to me except that the text in the buttons should be all uppercase -> "NO, THANKS" and "YES".
