### ISSUE TITLE
Fix YouTube Topsite caption

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4696]
YouTube's topsite caption should be "YouTube" instead of "Youtube". (Captial T)
We'll need to change this ASAP so that YouTube's API Services can proceed.

**Comment by mxlius** [comment]
I think it's duplicate with #4680. I'll close it, for now, if anyone thinks it's not a dup, please provide more detail and re-open it.

@youwenliang And also, please help to provide more detailed information from the issue template. Otherwise, we don't know where the string is and is it remote resources.

**Comment by youwenliang** [comment]
@mxlius thanks for the clarification. Yes this is a duplicate bug, sorry for the confusion.

**Comment by Daisy-pliu** [comment]
verify: ✅
version: 2.1.9 (18652) release
see correct "YouTube" naming on topsite
