### ISSUE TITLE
test(SwitchSearchEngineTest): not labelled as flaky

### ISSUE THREAD

**Issue by yxliang01** [mozilla-tw/FirefoxLite#4944]
**Describe the bug**
This report is about test cases in a test class that are not annotated as flaky but in fact it is. There is race condition between the search engine loading and the call at https://github.com/mozilla-tw/FirefoxLite/blob/32ddedf67826e13ae0c6dd3591117f5020daebd4/app/src/androidTest/java/org/mozilla/focus/activity/SwitchSearchEngineTest.java#L82 . Test case will fail if the call happens before the execution of https://github.com/mozilla-tw/FirefoxLite/blob/2f0b0c7d13c1fd8f98d8f1b80060591d629ed4e9/app/src/main/java/org/mozilla/focus/search/SearchEngineManager.java#L80 .

**Steps To Reproduce**
Run the test cases, eventually race condition can happen.

**Expected behavior**
Either we move the line https://github.com/mozilla-tw/FirefoxLite/blob/2f0b0c7d13c1fd8f98d8f1b80060591d629ed4e9/app/src/main/java/org/mozilla/focus/search/SearchEngineManager.java#L80 to https://github.com/mozilla-tw/FirefoxLite/blob/2f0b0c7d13c1fd8f98d8f1b80060591d629ed4e9/app/src/main/java/org/mozilla/focus/search/SearchEngineManager.java#L70 , or label the test case as flaky.

**Actual behavior**
Sometimes, the test case fails due to race condition.

**Comment by Daisy-pliu** [comment]
Thanks for raising out. 
In Firefox Lite , the tests we mark @Flaky means it failed from time to time, they are flaky on our CI so we won't run there whenever source code changes, instead we will run those flaky tests manually before we release a build.
Since we have not yet encountered race condition on this test on CI, we may keep monitor it . When it fails due to race condition that you pointed out we will make changes on it.
Appreciate for finding it and give great suggestion to us.

**Comment by zhendong2050** [comment]
Dear @Daisy-pliu,

I encountered this case as well. When running test(SwitchSearchEngineTest), the following exception might occur due to a synchronization issue: 

throw new IllegalStateException("Attempting to retrieve search engines without a corresponding init()"); at [link](https://github.com/mozilla-tw/FirefoxLite/blob/2f0b0c7d13c1fd8f98d8f1b80060591d629ed4e9/app/src/main/java/org/mozilla/focus/search/SearchEngineManager.java#L173)

The reason is as follows:
Method  getDefaultSearchEngine first checks whether the global variable "loadHasBeenTriggered" is TRUE. If not TRUE, an exception is thrown. 

The value of variable "loadHasBeenTriggered" is flipped to TRUE in method loadFromDisk.

 However, method loadFromDisk is executed in a WorkerThread (a background thread), and method getDefaultSearchEngine is executed in UI thread. There is  no synchronization between these two threads. Thus, Method getDefaultSearchEngine might check the value of variable "loadHasBeenTriggered" before method loadFromDisk in the WorkThread flips the variable as TRUE, which leads to the exception above.

I also could deterministically reproduce it by adding a little delay (200ms) before the following line.  

https://github.com/mozilla-tw/FirefoxLite/blob/2f0b0c7d13c1fd8f98d8f1b80060591d629ed4e9/app/src/main/java/org/mozilla/focus/search/SearchEngineManager.java#L80

The delay sleeps WorkThread for 200ms such that the error occurs for every test run.

Can you please check the case I reported? thank you.

**Comment by Daisy-pliu** [comment]
We hear your concerns and do you mind to push a PR so that our engineering could help on reviewing and providing feedback on it. The priority for this issue might not be the highest at this moment in our roadmap but we can find some better timing to have a look into it.  Many thanks .
