### ISSUE TITLE
[Home customization] Effort evaluation

### ISSUE THREAD

**Issue by youwenliang** [mozilla-tw/FirefoxLite#4967]
**Documents:** 
Part 1:
https://docs.google.com/document/d/1PTG6ZUhDh3qP8_xm5jVf4PiIoM0dexgc_PqCEvBYQzA/edit#
Overall:
https://docs.google.com/document/d/1oRQdJNIAESj8JNgjVL7DZLd6pIimfzUrZaZVaUSgs1g/edit#heading=h.pn2zusju29e4

We will provide basic user flows today for effort evaluation.

**Comment by proevan** [comment]
about 2 sprint work, still need to confirm the design of top site adding button

**Comment by tinahsieh** [comment]
Hey @proevan I couldn't discuss the adding button with you yesterday, so I briefly write it here. I'll visualize it on the UX spec so that it'll be more clear for you:

The top site adding button will be placed on the home menu, and there will be a snack bar showing when a top site successfully added. Users can tap on the "add more" button on the snack bar to continue adding another top site.

**Comment by proevan** [comment]
do we still need an animation when a top site added?

**Comment by tinahsieh** [comment]
Yes, but we can discuss if we can't do it all at once.

**Comment by chianger** [comment]
Investigation efforts done
