### ISSUE TITLE
 Firefox Lite Q2 Healthy check - App size

### ISSUE THREAD

**Issue by shsu571** [mozilla-tw/FirefoxLite#4989]
We are going to add more feature this season for keeping our app light.
We need to check the every feature size beofre our new feature implement.
We would also like to add Glean (700K).

**Comment by cnevinc** [comment]
<WIP>

### APK  

| File | Download Size | % of Download Size |
| --------- | ---------- | -------- | 
|     code    |  3.5 MB     | 39%      | 
|     res       |  1016.4KB     | 19.5%      | 
|     /res/drawable-xxhdpi-v4       |  474.4KB     | 9.1%      | 
|     /res/layout       |  145.4KB     | 2.8%      | 
|     /res/drawable       |  142.6KB     | 2.7%      | 
|     /res/raw    |  88.1KB     | 1.7%      | 
|     .......       | ...... | ..... |  
|     assets       | 235.5KB | 4.5% |  
|     assets/topsites       | 179.9KB | 3.5% |  
|     .......       | ...... | ..... |  
|     resource.arsc  |  195.6KB     | 3.5%      | 
### code
![image](https://user-images.githubusercontent.com/1287363/82546350-8f49ec00-9b8a-11ea-869e-c54beacc45db.png)

**Comment by cnevinc** [comment]
<WIP>

### APK  

| File | Download Size | % of Download Size |
| --------- | ---------- | -------- | 
|     code    |  2.2 MB     | 66.4%      | 
|     res       |  684.6KB     | 20.5%      | 
|     /res/drawable-xxhdpi-v4       |  264.1KB     | 7.9%      | 
|     /res/drawable       |  92.8KB     | 2.8%      | 
|     /res/layout       |  85.7KB     | 2.6%      | 
|     /res/raw    |  61.8KB     | 1.8%      | 
|     .......       | ...... | ..... |  
|     assets       | 181.5KB | 5.4% |  
|     assets/topsites       | 111.1KB | 3.3% |  
|     .......       | ...... | ..... |  
|     resource.arsc  |  154.7KB     | 4.6%      | 

### Code
![image](https://user-images.githubusercontent.com/1287363/82626187-b8fe2400-9c19-11ea-9111-f729589ad125.png)

**Comment by cnevinc** [comment]
## v 1.9.2

### APK  

| File | Download Size | % of Download Size |
| --------- | ---------- | -------- | 
|     code    |  2.2 MB     | 66.4%      | 
|     res       |  684.6KB     | 20.5%      | 
|     /res/drawable-xxhdpi-v4       |  264.1KB     | 7.9%      | 
|     /res/drawable       |  92.8KB     | 2.8%      | 
|     /res/layout       |  85.7KB     | 2.6%      | 
|     /res/raw    |  61.8KB     | 1.8%      | 
|     .......       | ...... | ..... |  
|     assets       | 181.5KB | 5.4% |  
|     assets/topsites       | 111.1KB | 3.3% |  
|     .......       | ...... | ..... |  
|     resource.arsc  |  154.7KB     | 4.6%      | 

### Code
![image](https://user-images.githubusercontent.com/1287363/82626187-b8fe2400-9c19-11ea-9111-f729589ad125.png)

**Comment by cnevinc** [comment]
If we remove some topsites, we might save a couple of bytes
![image](https://user-images.githubusercontent.com/1287363/82797998-7e5eea80-9eaa-11ea-8136-feb2bf98781c.png)

**Comment by cnevinc** [comment]
If we convert some png to webp, we might save ~57 KB
https://github.com/mozilla-tw/FirefoxLite/pull/5002

**Comment by cnevinc** [comment]
According to the APK Size History:
| version | size | feature |
| ----- | ----- | ----- |
| v 1.9.2 | 3.56 MB | Firefox Lite 1.0 |
| v 2.0.2 | 4.3 MB | MSRP / Vertical |
| v 2.0.5 | 5.26 MB | In-App-Message |
| v 2.1.7 | 5.48 MB | Smart shopping search / customize news... |

The culprit is IAM we added in #4414 
Suggestion:
1. Remove unused TopSites 
2. Convert png to WebP  (we'll save ~57 KB)
3. Remove unused code. For example
  - new feature onboarding code and assets (for upgrade user.)
  - MSRP
  - Unused vertical code
3. To avoid manual checks like this time in the future, let's add an APK size log for each PR, so it'll be much easier to track the size and the cause.
4. Use [Dynamic Feature](https://developer.android.com/guide/app-bundle/dynamic-delivery#customize_delivery) to make our APK size appears smaller on Play Store, or uninstall unused module to save the user's phone storage.

**Comment by chianger** [comment]
Investigation efforts done
